name: Deploy to AWS CodeArtifact

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para o commit da nova versão

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CodeArtifact login
        run: |
          aws codeartifact login \
            --tool maven \
            --domain ${{ vars.CA_DOMAIN }} \
            --domain-owner 148206343556 \
            --repository ${{ vars.CA_REPOSITORY }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Build (clean + install)
        run: mvn -B clean install -DskipTests

      - name: Increment patch version
        id: bump
        run: |
          echo "🔍 Current version:"
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $CURRENT_VERSION"

          # Quebra a versão em partes (major.minor.patch)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          # Incrementa o patch
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"

          echo "New version: $NEW_VERSION"

          # Atualiza o POM sem backup
          mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false

          # Exporta a nova versão para os próximos steps
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit new version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pom.xml
          git commit -m "ci: bump version to ${{ steps.bump.outputs.new_version }}"
          git push origin main

      - name: Publish to CodeArtifact
        run: mvn -B -U -DskipTests deploy